
# Database server settings
db:
    # or postgresql
    db_type: mysql
    db_server: localhost
    db_user: root
    db_passwd: password
    db_name: 'elki1_{{t}}'
    db_prefix: 'elk_{{t}}_'

# admin user
admin:
    username: 'Homer Simpson'
    password1: qwerty
    password2: qwerty
    email: 'homersimpson@admin.com'
    # db password
    password3: password
    # 0 - Unknown, 1- Male, 2 - Female
    gender: 1

forum:
    name: 'Ёлки - Палки'

# https://bitbucket.org/interlab/elga/get/dev.zip
# https://github.com/Spuds/Elk_FancyBox/archive/master.zip
